workflows:
  build_nativescript_apk:
    name: Build NativeScript APK
    max_build_duration: 60
    environment:
      node: 20
    scripts:
      - name: Install dependencies
        script: npm install -g nativescript
      - name: Build NativeScript Android APK
        script: tns build android --release --keyStorePath $CM_KEYSTORE_PATH --keyStorePassword $CM_KEYSTORE_PASSWORD --keyStoreAlias $CM_KEYSTORE_ALIAS --keyStoreAliasPassword $CM_KEYSTORE_ALIAS_PASSWORD
    artifacts:
      - platforms/android/app/build/outputs/**/*.apk
