name: Build NativeScript APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install NativeScript CLI (local + global fallback)
        run: |
          # instala en local (proyecto) y también intenta global para compatibilidad
          npm install nativescript --no-save || true
          npm install -g nativescript || true
          ./node_modules/.bin/ns --version || npx ns --version

      - name: Install project dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci --silent
          else
            npm install --silent
          fi

      - name: Set up JDK (Java 11)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Android SDK (required build tools & platform)
        uses: android-actions/setup-android@v3
        with:
          api-levels: 30
          build-tools: '30.0.3'

      - name: Build Debug APK (NativeScript)
        run: |
          echo "=== PATH ==="
          echo $PATH
          echo "=== NS version ==="
          # usa el binario local si está, si no usa npx
          if [ -x ./node_modules/.bin/ns ]; then
            ./node_modules/.bin/ns build android --debug --no-hmr --no-watch
          else
            npx ns build android --debug --no-hmr --no-watch
          fi
        env:
          # evita prompts interactivos
          CI: true

      - name: List output folders and find APKs (debug step)
        run: |
          echo "=== list platforms directory ==="
          ls -laR platforms || true
          echo "=== find any apk files ==="
          find . -type f -name "*.apk" -print || true

      - name: Upload APK artifact (only on success)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: |
            platforms/android/app/build/outputs/apk/debug/*.apk
            platforms/**/build/outputs/apk/**/*.apk
            **/*.apk
