name: Build NativeScript APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install NativeScript CLI
        run: npm install -g nativescript

      - name: Install dependencies
        run: npm install

      - name: Build Android APK
        run: ns build android

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: nativescript-apk
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
